services:
  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - API_HOST=http://backend:8000
      - PORT=8002
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/myapp
      - PORT=8000
    depends_on:
      - mongodb

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/myapp
      - PORT=8001
      - REACT_APP_API_BASE_URL=http://backend:8000
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: